# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_node_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addNodeDlg(object):
    def setupUi(self, addNodeDlg):
        addNodeDlg.setObjectName("addNodeDlg")
        addNodeDlg.resize(185, 100)
        self.verticalLayout = QtWidgets.QVBoxLayout(addNodeDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(addNodeDlg)
        font = QtGui.QFont()
        font.setFamily("霞鹜文楷 屏幕阅读版 R")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_name = QtWidgets.QLineEdit(addNodeDlg)
        font = QtGui.QFont()
        font.setFamily("霞鹜文楷 屏幕阅读版 R")
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setPlaceholderText("")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout.addWidget(self.lineEdit_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_initialState = QtWidgets.QCheckBox(addNodeDlg)
        font = QtGui.QFont()
        font.setFamily("霞鹜文楷 屏幕阅读版 R")
        self.checkBox_initialState.setFont(font)
        self.checkBox_initialState.setObjectName("checkBox_initialState")
        self.horizontalLayout_2.addWidget(self.checkBox_initialState)
        self.checkBox_middleState = QtWidgets.QCheckBox(addNodeDlg)
        font = QtGui.QFont()
        font.setFamily("霞鹜文楷 屏幕阅读版 R")
        self.checkBox_middleState.setFont(font)
        self.checkBox_middleState.setAutoFillBackground(False)
        self.checkBox_middleState.setChecked(True)
        self.checkBox_middleState.setObjectName("checkBox_middleState")
        self.horizontalLayout_2.addWidget(self.checkBox_middleState)
        self.checkBox_finalState = QtWidgets.QCheckBox(addNodeDlg)
        font = QtGui.QFont()
        font.setFamily("霞鹜文楷 屏幕阅读版 R")
        self.checkBox_finalState.setFont(font)
        self.checkBox_finalState.setObjectName("checkBox_finalState")
        self.horizontalLayout_2.addWidget(self.checkBox_finalState)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(addNodeDlg)
        font = QtGui.QFont()
        font.setFamily("霞鹜文楷 屏幕阅读版 R")
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(addNodeDlg)
        self.buttonBox.accepted.connect(addNodeDlg.accept) # type: ignore
        self.buttonBox.rejected.connect(addNodeDlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addNodeDlg)

    def retranslateUi(self, addNodeDlg):
        _translate = QtCore.QCoreApplication.translate
        addNodeDlg.setWindowTitle(_translate("addNodeDlg", "NodeInfo"))
        self.label.setText(_translate("addNodeDlg", "状态名"))
        self.checkBox_initialState.setText(_translate("addNodeDlg", "初态"))
        self.checkBox_middleState.setText(_translate("addNodeDlg", "中间态"))
        self.checkBox_finalState.setText(_translate("addNodeDlg", "终态"))
